/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.app;

private
{
    import std.stdio;
    import std.conv;
    import std.string;
    import std.process;
    import std.algorithm;
    import std.math;

    import derelict.util.compat;
    import derelict.sdl.sdl;
    import derelict.opengl.gl;
    import derelict.opengl.glu;
    import derelict.opengl.glext;
    import derelict.freetype.ft;

    import dlib.image.io.png;

    import engine.core.application;
    import engine.graphics.texture;
    
    import engine.board;
    import engine.cell;
}

class ArrowApp: Application
{
    Board board;

    this(uint w, uint h, string caption)
    {   
        super(w, h, caption);

        glClearColor(0.4f, 0.4f, 0.4f, 1.0f);

        glDisable(GL_LIGHTING);

        manager.bindActionToEvent(EventType.KeyDown, &onKeyDown);
        manager.bindActionToEvent(EventType.KeyUp, &onKeyUp);
        manager.bindActionToEvent(EventType.Resize, &onResize);
        manager.bindActionToEvent(EventType.MouseButtonDown, &onMouseButtonDown);
        
        board = new Board();
    }

    void onResize()
    {
    }

    void onMouseButtonDown()
    {
    }
    
    void onKeyDown()
    {
        if (manager.event_key == SDLK_ESCAPE)
        {
            manager.running = false;
        }
        else if (manager.event_key == SDLK_RETURN)
        {
            if (board.gameState == 1)
                board.restart();
            else
                board.pause();
        }
        else if (manager.event_key == SDLK_LEFT)
        {
            board.piece.moveLeft();
        }
        else if (manager.event_key == SDLK_RIGHT)
        {
            board.piece.moveRight();
        }
        else if (manager.event_key == SDLK_SPACE)
        {
            board.piece.rotateCW();
        }
        else if (manager.event_key == SDLK_DOWN)
        {
            board.dropPiece();
        }
        else if (manager.event_key == '1')
        {
            board.setNext(Cell.State.Omni);
        }
    }

    void onKeyUp()
    {
        if (manager.event_key == SDLK_DOWN)
        {
            board.undropPiece();
        }
    }

    override void onUpdate()
    {               
        // Draw everything
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        glLoadIdentity();

        // 2D mode
        glColor3f(1.0f, 1.0f, 1.0f);
        
        board.draw(manager.deltaTime);

        //tex.bind(manager.deltaTime);
        //drawRectangle(0, 0, tex.width, tex.height);
        //tex.unbind();
    }

    void drawRectangle(float x, float y, float w, float h)
    {
        glPushMatrix();
        glTranslatef(x, y, 0.0f);
        glScalef(w, h, 1.0f);
        glBegin(GL_QUADS);
	    glTexCoord2f(0.0f, 0.0f); glVertex2f(0.0f, 0.0f);
	    glTexCoord2f(1.0f, 0.0f); glVertex2f(1.0f, 0.0f);
	    glTexCoord2f(1.0f, 1.0f); glVertex2f(1.0f, 1.0f);
	    glTexCoord2f(0.0f, 1.0f); glVertex2f(0.0f, 1.0f);
        glEnd();
        glPopMatrix();
    }
}


