/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.cell;

private
{
    import engine.wrnd;
}

struct Cell
{
    enum State
    {
        Empty,
        Left,
        Right,
        Up,
        Down,
        Horizontal,
        Vertical,
        Omni,
        Stone,
        Highlight
    }
    
    enum Proportions
    {
        Empty      = 0,
        Left       = 10,
        Right      = 10,
        Up         = 10,
        Down       = 10,
        Horizontal = 7,
        Vertical   = 7,
        Omni       = 5,
        Stone      = 3,
        Highlight = 0
    }
    
    State state = State.Empty;
    bool frozen = false;

    bool markToFree = false;
    bool markToRotate = false;

    bool disappearing = false;
    float scale = 1.0f;

    bool rotating = false;
    float rot = 0.0f;

    State nextState = State.Empty;
    
    static float disappearTime = 0.3f;//1.0f;
    float timer = 0.0f;
    
    void setRandomState()
    {
        state = randomState();
    }

    static State randomState()
    {
        return weightedRandomEnum!(State, Proportions)();
    }

    void free()
    {
        disappearing = true;
    }

    State clockwiseRotState(State s)
    {
        if (s == State.Right) s = State.Down;
        else if (s == State.Down)  s = State.Left;
        else if (s == State.Left)  s = State.Up;
        else if (s == State.Up)    s = State.Right;
        else if (s == State.Horizontal) s = State.Vertical;
        else if (s == State.Vertical) s = State.Horizontal;
        return s;
    }

    void rotate()
    {
        if (state == State.Stone)
        {
            disappearing = true;
            markToRotate = false;
        }
        else if (state != State.Omni)
        {
            rotating = true;
            nextState = clockwiseRotState(state);
        }
        else
        {
            markToRotate = false;
        }
    }

    void update(double delta)
    {
        if (disappearing)
        {
            float spd = 1.0f / disappearTime;
            scale -= spd * delta; //3.0f * delta;
            if (scale <= 0.0f)
            {
                scale = 1.0f;
                disappearing = false;
                state = State.Empty;
                markToFree = false;
            }
        }
        if (rotating)
        {
            float spd = 90.0f / disappearTime;
            rot -= spd * delta;

            if (rot <= -90.0f)
            {
                rot = 0.0f;
                rotating = false;

                state = nextState;
                nextState = State.Empty;

                markToRotate = false;
            }
        }
    }
}

bool isHorizontal(Cell.State s)
{
    return 
       (s == Cell.State.Left ||
        s == Cell.State.Right ||
        s == Cell.State.Horizontal ||
        s == Cell.State.Omni);
}

bool isVertical(Cell.State s)
{
    return 
       (s == Cell.State.Up ||
        s == Cell.State.Down ||
        s == Cell.State.Vertical ||
        s == Cell.State.Omni);
}

bool sameDirection(Cell.State s1, Cell.State s2)
{
    if (s1 == s2)
        return true;

    if (s1 == Cell.State.Left && s2 == Cell.State.Horizontal)
        return true;
    if (s1 == Cell.State.Right && s2 == Cell.State.Horizontal)
        return true;
    if (s1 == Cell.State.Horizontal && s2 == Cell.State.Left)
        return true;
    if (s1 == Cell.State.Horizontal && s2 == Cell.State.Right)
        return true;

    if (s1 == Cell.State.Up && s2 == Cell.State.Vertical)
        return true;
    if (s1 == Cell.State.Down && s2 == Cell.State.Vertical)
        return true;
    if (s1 == Cell.State.Vertical && s2 == Cell.State.Up)
        return true;
    if (s1 == Cell.State.Vertical && s2 == Cell.State.Down)
        return true;

    if (s1 == Cell.State.Left && s2 == Cell.State.Omni)
        return true;
    if (s1 == Cell.State.Right && s2 == Cell.State.Omni)
        return true;
    if (s1 == Cell.State.Up && s2 == Cell.State.Omni)
        return true;
    if (s1 == Cell.State.Down && s2 == Cell.State.Omni)
        return true;

    if (s1 == Cell.State.Omni && s2 == Cell.State.Left)
        return true;
    if (s1 == Cell.State.Omni && s2 == Cell.State.Right)
        return true;
    if (s1 == Cell.State.Omni && s2 == Cell.State.Up)
        return true;
    if (s1 == Cell.State.Omni && s2 == Cell.State.Down)
        return true;

    if (s1 == Cell.State.Horizontal && s2 == Cell.State.Omni)
        return true;
    if (s1 == Cell.State.Vertical && s2 == Cell.State.Omni)
        return true;

    if (s1 == Cell.State.Omni && s2 == Cell.State.Horizontal)
        return true;
    if (s1 == Cell.State.Omni && s2 == Cell.State.Vertical)
        return true;

    return false;
}

bool isConcrete(Cell.State s)
{
    return(
       s == Cell.State.Left ||
       s == Cell.State.Right ||
       s == Cell.State.Up ||
       s == Cell.State.Down);
}

