/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.grid;

private
{
    import engine.cell;
}

class Grid
{
    uint width;
    uint height;

    Cell[] grid;
    alias grid this;

    this(uint w, uint h)
    {
        width = w;
        height = h;
        grid = new Cell[width*height];
    }

    void empty()
    {
        foreach(ref c; grid)
            c.state = Cell.State.Empty;
    }

    bool cellIsEmpty(int x, int y)
    {
        if (x < 0 || x > width-1 || y < 0 || y > height-1)
            return false;

        uint i = cast(uint)(y * width + x);
        if (grid[i].state != Cell.State.Empty)
            return false;

        return true;
    }

    bool positionValid(int x, int y)
    {
        return(
            x >= 0 && x < width &&
            y >= 0 && y < height);
    }

    Cell.State cellState(uint x, uint y)
    {
        uint i = width * y + x;
        return grid[i].state;
    }

    void markRowToFree(uint row, uint start, uint end)
    {
        foreach(x; start..end)
        {
            uint i = row * width + x;
            if (grid[i].state != Cell.State.Empty)
                grid[i].markToFree = true;
        }
    }

    void markColumnToFree(uint col, uint start, uint end)
    {
        foreach(y; start..end)
        {
            uint i = y * width + col;
            if (grid[i].state != Cell.State.Empty)
                grid[i].markToFree = true;
        }
    }

    bool haveMarkedCells()
    {
        foreach(ref c; grid)
        {
            if (c.markToFree)
                return true;
        }
        return false;
    }
    
    bool haveRotateMarkedCells()
    {
        foreach(ref c; grid)
        {
            if (c.markToRotate)
                return true;
        }
        return false;
    }

    void deleteLines()
    {
        foreach(ref c; grid)
        {
            if (c.markToFree)
                c.free();
        }
    }

    bool dropCells()
    {
        bool result = false;
        foreach(y; 0..height)
        foreach(x; 0..width)
        {
            int i = y * width + x;
            int i2 = (y + 1) * width + x;
            if (y < height-1)
            {
                if (grid[i].state != Cell.State.Empty &&
                    !grid[i2].markToFree &&
                    !grid[i2].disappearing &&
                    grid[i2].state == Cell.State.Empty &&
                    !grid[i2].markToFree &&
                    !grid[i2].disappearing)
                {
                    grid[i2].state = grid[i].state;
                    grid[i].state = Cell.State.Empty;
                    result = true;
                }
            }
        }

        return result;
    }
    
    bool sameDirectionHor(Cell*[3] cells)
    {
        int[3] rate = 0;
        
        foreach(i, c; cells)
        {
            auto s = c.state;
        
            if (isHorizontal(s))
            {
                if (s == Cell.State.Left)
                    rate[i] = -1;
                else if (s == Cell.State.Right)
                    rate[i] = 1;
            }
            else
                return false;
        }

        int firstNonZero = 0;
        foreach(r; rate)
        {
            if (r != 0 && firstNonZero == 0)
                firstNonZero = r;
            else
            {
                if (r != firstNonZero)
                    return false;
            }
        }
        
        return true;
    }
    
    bool sameDirectionVer(Cell*[3] cells)
    {
        int[3] rate = 0;
        
        foreach(i, c; cells)
        {
            auto s = c.state;
        
            if (isVertical(s))
            {
                if (s == Cell.State.Up)
                    rate[i] = -1;
                else if (s == Cell.State.Down)
                    rate[i] = 1;
            }
            else
                return false;
        }

        int firstNonZero = 0;
        foreach(r; rate)
        {
            if (r != 0 && firstNonZero == 0)
                firstNonZero = r;
            else
            {
                if (r != firstNonZero)
                    return false;
            }
        }
        
        return true;
    }

    bool detectLines()
    {
        Cell* director;
        
        director = null;
        for(uint y = 0; y < height; y++)
        {
            uint xstart = 0;
            Cell* firstNonConcrete = null;
            uint ncx = 0;
            
            for(uint x = 0; x < width; x++)
            {
                uint i = y * width + x;
                auto s = grid[i].state;
                bool valid = true;
                bool checkThis = true;
                
                if (isHorizontal(s))
                {                
                    if (!isConcrete(s) &&
                        firstNonConcrete is null)
                    {
                        ncx = x;
                        firstNonConcrete = &grid[i];
                    }
                
                    if (director is null)
                    {
                        if (isConcrete(s))
                        {
                            director = &grid[i];
                            firstNonConcrete = null;
                        }
                    }
                    else if (isConcrete(s))
                    {
                        if (!sameDirection(s, director.state))
                        {
                            if (x - xstart >= 3)
                                markRowToFree(y, xstart, x);
                                
                            if (firstNonConcrete !is null)
                                xstart = ncx;
                            else
                                xstart = x;
                                
                            director = &grid[i];

                            firstNonConcrete = null;
                        }
                        else
                        {
                            firstNonConcrete = null;
                        }
                    }
                }
                else
                {
                    if (x - xstart >= 3)
                        markRowToFree(y, xstart, x);

                    xstart = x+1;
                    director = null;
                    firstNonConcrete = null;
                }
            }
            
            if (width - xstart >= 3)
                markRowToFree(y, xstart, width);
        }
        
        director = null;
        for(uint x = 0; x < width; x++)
        {
            uint ystart = 0;
            Cell* firstNonConcrete = null;
            uint ncy = 0;
            
            for(uint y = 0; y < height; y++)
            {
                uint i = y * width + x;
                auto s = grid[i].state;
                bool valid = true;
                bool checkThis = true;
                
                if (isVertical(s))
                {               
                    if (!isConcrete(s) &&
                        firstNonConcrete is null)
                    {
                        ncy = y;
                        firstNonConcrete = &grid[i];
                    }
                
                    if (director is null)
                    {
                        if (isConcrete(s))
                        {
                            director = &grid[i];
                            firstNonConcrete = null;
                        }
                    }
                    else if (isConcrete(s))
                    {
                        if (!sameDirection(s, director.state))
                        {
                            if (y - ystart >= 3)
                                markColumnToFree(x, ystart, y);
                                
                            if (firstNonConcrete !is null)
                                ystart = ncy;
                            else
                                ystart = y;
                                
                            director = &grid[i];

                            firstNonConcrete = null;
                        }
                        else
                        {
                            firstNonConcrete = null;
                        }
                    }
                }
                else
                {
                    if (y - ystart >= 3)
                        markColumnToFree(x, ystart, y);

                    ystart = y+1;
                    director = null;
                    firstNonConcrete = null;
                }
            }
            
            if (height - ystart >= 3)
                markColumnToFree(x, ystart, height);
        }
        
        return haveMarkedCells();
    }

    Cell* getNeighbour(int x, int y, int nx, int ny)
    {
        auto x1 = x + nx;
        auto y1 = y + ny;
        if (x1 < width && x1 >= 0 &&
            y1 < height && y1 >= 0)
        {
            uint i = cast(uint)(y1 * width + x1);
            return &grid[i];
        }
        else
            return null;
    }

    void markNeighboursToRotate()
    {
        foreach(y; 0..height)
        foreach(x; 0..width)
        {
            uint i = y * width + x;
            if (grid[i].state != Cell.State.Empty &&
                grid[i].markToFree)
            {
                auto nRight = getNeighbour(x, y, 1, 0);
                auto nLeft  = getNeighbour(x, y,-1, 0);
                auto nUpper = getNeighbour(x, y, 0, 1);
                auto nLower = getNeighbour(x, y, 0,-1);

                if (nRight !is null)
                if (!nRight.markToFree)
                if (nRight.state != Cell.State.Empty)
                    nRight.markToRotate = true;

                if (nLeft !is null)
                if (!nLeft.markToFree)
                if (nLeft.state != Cell.State.Empty)
                    nLeft.markToRotate = true;

                if (nUpper !is null)
                if (!nUpper.markToFree)
                if (nUpper.state != Cell.State.Empty)
                    nUpper.markToRotate = true;

                if (nLower !is null)
                if (!nLower.markToFree)
                if (nLower.state != Cell.State.Empty)
                    nLower.markToRotate = true;
            }
        }
    }

    void rotateMarked()
    {
        foreach(ref c; grid)
        {
            if (c.markToRotate)
                c.rotate();
        }
    }
}

